# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _camvox
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class Interval(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Interval, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Interval, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _camvox.new_Interval(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _camvox.delete_Interval
    __del__ = lambda self : None;
Interval_swigregister = _camvox.Interval_swigregister
Interval_swigregister(Interval)

class Vector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Vector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Vector, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _camvox.new_Vector(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _camvox.delete_Vector
    __del__ = lambda self : None;
    def x_get(*args): return _camvox.Vector_x_get(*args)
    def x_set(*args): return _camvox.Vector_x_set(*args)
    def y_get(*args): return _camvox.Vector_y_get(*args)
    def y_set(*args): return _camvox.Vector_y_set(*args)
    def z_get(*args): return _camvox.Vector_z_get(*args)
    def z_set(*args): return _camvox.Vector_z_set(*args)
    def w_get(*args): return _camvox.Vector_w_get(*args)
    def w_set(*args): return _camvox.Vector_w_set(*args)
Vector_swigregister = _camvox.Vector_swigregister
Vector_swigregister(Vector)

class Matrix(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Matrix, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Matrix, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _camvox.new_Matrix(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _camvox.delete_Matrix
    __del__ = lambda self : None;
Matrix_swigregister = _camvox.Matrix_swigregister
Matrix_swigregister(Matrix)



