<?xml version="1.0 encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>camvox - $title</title>
  <meta http-equiv="content-type" content="text/html;charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <link rel="stylesheet" href="include/camvox.css" type="text/css"/>
 </head>
  <body>
<div class="title">
CAM.VOX
</div>
<div class="menu">
<span class="menu"><a href="index.html">home</a></span>
<span class="menu"><a href="download.html">download</a></span>
<span class="menu"><a href="documentation.html">documentation</a></span>
<span class="menu"><a href="contact.html">contact</a></span>
</div>
<img class="corner_image" src="include/corner_image.png" alt="corner image"/>

