<?xml version="1.0 encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>camvox - $title</title>
  <meta http-equiv="content-type" content="text/html;charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <link rel="stylesheet" href="include/camvox.css" type="text/css"/>
 </head>
  <body>
<table class="title"><tr>
<td class="title_logo"><a href="http://camvox.sourceforge.net"><img width="189" height="37" src="images/logo.gif" alt="logo"/></a></td>
<td class="title_middle"></td>
<td class="title_sourceforge"><a href="http://sourceforge.net"><img src="http://sflogo.sourceforge.net/sflogo.php?group_id=235658&amp;type=2" width="125" height="37" alt="SourceForge.net Logo" /></a></td>
</tr></table>
<table class="menu"><tr>
<td class="menu"><a href="index.html">home</a></td>
<td class="menu"><a href="http://sourceforge.net/projects/camvox/">project pages</a></td>
<td class="menu"><a href="download.html">download</a></td>
<td class="menu"><a href="documentation.html">documentation</a></td>
<td class="menu"><a href="contact.html">contact</a></td>
<td class="menu_last">&nbsp</td>
</tr></table>
<img class="corner_image" src="include/corner_image.png" alt="corner image"/>

