
CXX=g++
CXXFLAGS=-g -DHAVE_INLINE
LD=gcc
LIBS=-lgsl
LDFLAGS=-g

TARGET=vgcam
OBJS=vgcam.o VoxNode.o
SRCS=vgcam.cpp VoxNode.cpp

all: $(TARGET)

clean:
	rm -f $(TARGET) $(OBJS)

depend:
	makedepend -- $(CFLAGS) -- $(SRCS)

$(TARGET): $(OBJS)
	$(LD) $(LDFLAGS) -o $(TARGET) $(OBJS) $(LIBS)

.cpp.o:
	$(CXX) $(CFLAGS) -c $<


# DO NOT DELETE

vgcam.o: /usr/include/stdlib.h /usr/include/available.h /usr/include/_types.h
vgcam.o: /usr/include/sys/_types.h /usr/include/sys/cdefs.h
vgcam.o: /usr/include/machine/_types.h /usr/include/i386/_types.h
vgcam.o: /usr/include/sys/wait.h /usr/include/sys/signal.h
vgcam.o: /usr/include/sys/appleapiopts.h /usr/include/machine/signal.h
vgcam.o: /usr/include/i386/signal.h /usr/include/i386/_structs.h
vgcam.o: /usr/include/sys/_structs.h /usr/include/machine/_structs.h
vgcam.o: /usr/include/sys/resource.h /usr/include/machine/endian.h
vgcam.o: /usr/include/i386/endian.h /usr/include/sys/_endian.h
vgcam.o: /usr/include/libkern/_OSByteOrder.h
vgcam.o: /usr/include/libkern/i386/_OSByteOrder.h /usr/include/alloca.h
vgcam.o: /usr/include/machine/types.h /usr/include/i386/types.h
vgcam.o: /usr/include/stdio.h Vector.h CSGSphere.h CSGObject.h Matrix.h
vgcam.o: CSGAABB.h
